[package]
name = "mauzi"
version = "0.1.0"
authors = ["Lukas Kalbertodt <lukas.kalbertodt@gmail.com>"]

[dependencies]
mauzi_macros = { path = "mauzi_macros/" }
mauzi_runtime = { path = "mauzi_runtime/" }
